### ISSUE TITLE
LNK2001 with optional abort and RID win-x86.

### ISSUE THREAD

**Issue by rico-erhard** [AaronRobinsonMSFT/DNNE#101]
Hello, it seems the optional abort override from 52edb718f49778406ce58c4b5fb6d426c0fb9ef4
leads to a LNK2001, when building for the win-x86 platform.
`platform.obj : error LNK2001: unresolved external symbol _dnne_abort [C:\source\dotnet\DNNE\Lib\Lib.csproj]`

I get this error when building a .NET5 classlib with one export
referencing a DNNE package built from 52edb718f49778406ce58c4b5fb6d426c0fb9ef4 as follows
`C:\source\dotnet\DNNE\Lib> dotnet build -f net5.0   -r win-x86`

Many thanks.

**Comment by AaronRobinsonMSFT** [comment]
@rico-erhard Thanks for reporting this. I've been able to reproduce this locally and will push up a fix soon. Seems I also need to update my CI to have an x86 leg 😄
