### ISSUE TITLE
Help with installing dependancies?

### ISSUE THREAD

**Issue by CoenraadS** [AaronRobinsonMSFT/DNNE#113]
Hello

I'm trying to simply compile an empty project `.net 6 classlib` referencing this nuget package on windows, and getting the following error:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
	<Platforms>x86</Platforms>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DNNE" Version="1.0.30" />
  </ItemGroup>

</Project>

```

![image](https://user-images.githubusercontent.com/5593825/162630356-2fe51b7f-4cba-40ed-9173-fe1833b9b0bb.png)

Using VS2022, I installed `Windows 10 SDK` & `Desktop development with C++` assuming this would install whatever compilers I need, but I'm a bit lost tbh

**Comment by AaronRobinsonMSFT** [comment]
If looks as if nothing was exported. Can you try exporting something simple and try again? DNNE has some UX issues for the no-op case. Exporting even the simplest method should be sufficient.

```csharp
public class Export
{
    [UnmanagedCallersOnly]
    public static void Func() { }
}
```

**Comment by CoenraadS** [comment]
Thanks! Indeed now it works
