### ISSUE TITLE
Question: <DnneWorkAroundSdk1675>true</DnneWorkAroundSdk1675> still needed to .Net 6

### ISSUE THREAD

**Issue by tvogel-nid** [AaronRobinsonMSFT/DNNE#114]
Hi,

it seems the issue has been closed for .Net 5 and 6, so do you think it is save to set this to false for projects targeting .Net 6 and above?

Thanks
Thomas

**Comment by AaronRobinsonMSFT** [comment]
It is worth a shot. I've not tried it yet either. Care to give it a go? If I recall the project referencing the DNNE component won't see all assets copied over.

**Comment by tvogel-nid** [comment]
it seems to work, at least for .NET 6 I can tell
