### ISSUE TITLE
Question: Export function with out parameter

### ISSUE THREAD

**Issue by CoenraadS** [AaronRobinsonMSFT/DNNE#125]
Hi, I'm trying to migrate code that previously used `DllExport` so it could be used by InnoSetup.

Previously I had 
```
[MarshalAs(UnmanagedType.LPWStr)] string input, [MarshalAs(UnmanagedType.BStr)] out string output
```

I can't make an `out IntPtr` though

```
  [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
        public static void ReturnString(IntPtr value, out IntPtr result)
        {
            var message = Marshal.PtrToStringUni(value);
            _ = NativeMethods.MsgBox(IntPtr.Zero, message, ":)", 0);

            result = Marshal.StringToBSTR("???"); 
        }
```

This required for interaction with Pascal/Delphi, where the return value is passed as parameter by reference when using `stdcall`: https://stackoverflow.com/a/9353800/4503491

**Comment by CoenraadS** [comment]
Solved with

```
  [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
        public static unsafe void ReturnString(IntPtr value, int* result)
        {
            var message = Marshal.PtrToStringUni(value);
            _ = NativeMethods.MsgBox(IntPtr.Zero, message, ":)", 0);

            var output = Marshal.StringToBSTR("???");
            var outPtr = new IntPtr(result);
            Marshal.WriteIntPtr(outPtr, output);
        }
```

**Comment by AaronRobinsonMSFT** [comment]
> `public static unsafe void ReturnString(IntPtr value, int* result)`

@CoenraadS This is a bit questionable if your previous API was using `out IntPtr`. Instead this should be:

```csharp
public static unsafe void ReturnString(IntPtr value, IntPtr* result)
{
    var message = Marshal.PtrToStringUni(value);
    _ = NativeMethods.MsgBox(IntPtr.Zero, message, ":)", 0);
    *result = Marshal.StringToBSTR("???");
}
```

**Comment by CoenraadS** [comment]
Thanks, I don't really know any `c` code so I'm just guessing a bit until something works. Will fix it on my end.

**Comment by AaronRobinsonMSFT** [comment]
> Thanks, I don't really know any `c` code so I'm just guessing a bit until something works. Will fix it on my end.

Oh, great. Please let me know if you need any help in this area. Some notes that might help.

The C# keywords `ref` and `out` represent levels of indirection so in C, they will both be converted to `*`. For example, `ref int` and `out int` both would be converted to `int*` in C. The `in` keyword is also by reference but treated as `const`.

The recommended int data types in C can be found in `stdint.h`. The mapping is as follows:

| C# | C |
|---|---|
|`sbyte`/`byte` | `int8_t`/`uint8_t`|
|`short`/`ushort` | `int16_t`/`uint16_t`|
|`int`/`uint` | `int32_t`/`uint32_t`|
|`long`/`ulong` | `int64_t`/`uint64_t`|
|`char` | `uint16_t` (only when passed through a pointer.)|
|`bool` | `int8_t`/`uint8_t`|
|`nint`/`nuint`|`intptr_t`/`uintptr_t`|

For x86 (32 bit), there are a few calling conventions be aware of. On Windows the Win32 API default is `Stdcall`, but the MSVC compiler defaults to `Cdecl`. On non-Windows, the default is almost always `Cdecl`. If you are targeting any 64-bit platform there is typically only one and if that is all you are targeting I'd simply leave the `UnmanagedCallersOnly` with no arguments.

**Comment by CoenraadS** [comment]
Thanks, I was using `stdcall` because the official InnoSetup interop example used it, but it seems `cdecl` works just as well, as has benefit I don't need to mess around with `.def` files.

I think I will probably build a small code generation layer ontop of DNNE so I abstract away these pointers and put marshal types in the signature, but thought first I would ask if something perhaps already exists?

**Comment by AaronRobinsonMSFT** [comment]
The default for x86 on Windows is `stdcall` but on non-Windows it is `cdecl`.

> I think I will probably build a small code generation layer ontop of DNNE so I abstract away these pointers and put out & marshal types in the signature, but thought first I would ask if something perhaps already exists?

When you say "on top of", I assume you mean to say that the method `UnmanagedCallersOnly` calls a method that uses the C# keyword - this is fine. If this isn't the case, please elaborate.
