### ISSUE TITLE
Question: A way to get a list of exported functions pre-compile time

### ISSUE THREAD

**Issue by CoenraadS** [AaronRobinsonMSFT/DNNE#126]
Hi, so I made a function using `stdcall`, but then it didn't work in my host application

I found this issue: https://github.com/AaronRobinsonMSFT/DNNE/issues/78

And indeed, after making a `.def` file with

```
EXPORTS
   Example=Example
```

It works. However I don't want to manually have to keep such a file in sync.

I'm looking for a way that

Pre-compile -> Get list of functions -> Then I can generate `.def` file -> Now compiler can run

**Comment by CoenraadS** [comment]
I made the current console app for now:

```
using DNNETest;
using System.Text;

var names = typeof(NativeExports).GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static).Select(m => m.Name).ToArray();

var output = new StringBuilder();
output.AppendLine("EXPORTS");

foreach (var name in names)
{
    output.AppendLine($"\t{name}={name}");
}

var result = output.ToString();
Console.WriteLine(result);
File.WriteAllText(@"SomeLocation\DnneWindowsExports.def", result);
```

But it would be great to achieve without required another project

**Comment by AaronRobinsonMSFT** [comment]
@CoenraadS I've thought about this issue more and I don't think this is something I am inclined to support. Your workaround above doesn't seem to be too much effort and targeting Windows-x86 is becoming more and more niche and not worth adding features for. I am open to revisiting this decision if others in the community show interest, but for now I am going to close the issue. Thanks for the suggestion.
