### ISSUE TITLE
The print result of MyClass_printNumber() is zero

### ISSUE THREAD

**Issue by ouyangyiluo** [AaronRobinsonMSFT/DNNE#129]
[class MyClass](https://github.com/AaronRobinsonMSFT/DNNE/blob/c2feaa898fe35587f6e5f692809dac05ce44e856/test/ExportingAssembly/InstanceExports.cs#L112)

**Comment by AaronRobinsonMSFT** [comment]
@ouyangyiluo Please expand on the issue being reported here. They are all zero because that is the initial value. Calling the properties in C++ can change that. Let me know what you've tried so far.

**Comment by ouyangyiluo** [comment]
> @ouyangyiluo请扩展此处报告的问题。它们都为零，因为那是初始值。在 C++ 中调用属性可以改变这一点。让我知道你到目前为止所做的尝试。


I am using
Visual Studio 2022 Preview
.NET 5.0。

My test result .

![CSharp](https://user-images.githubusercontent.com/51234993/172771544-6386a46d-1a3c-4160-b47d-f71228b3b169.png)


![CPP](https://user-images.githubusercontent.com/51234993/172772191-6882cadd-9a69-4875-8dfb-27ca61bf37ef.png)



After trying to modify the code, the test result is the same as that of C#
`    public class MyClass
    {
        public MyClass()
        {
            Number = 0;
        }

        public int Number { get; set; }

        public void PrintNumber() => Console.WriteLine(Number);
    }`

![CPP2](https://user-images.githubusercontent.com/51234993/172772196-fc5dcbdd-3b4c-464a-94ee-9276727e1c4f.png)
