### ISSUE TITLE
Starting the runtime fails.

### ISSUE THREAD

**Issue by alberts2** [AaronRobinsonMSFT/DNNE#13]
Starting the runtime fails sometimes because of a issue in the `get_current_dir_filepath` function
https://github.com/AaronRobinsonMSFT/DNNE/blob/449e4cc45ca79ceac477684cbd0cca7a275592e6/src/platform/platform.c#L291
Should probably be
`int32_t remaining = (int32_t)DNNE_MAX_PATH - (filename_dest - buffer);`

**Comment by AaronRobinsonMSFT** [comment]
@alberts2 The length of the buffer is passed in so I think it could be the following:

`int32_t remaining = len - (filename_dest - buffer);`

Thanks for reporting this. I will push up a new version ASAP.

**Comment by AaronRobinsonMSFT** [comment]
@alberts2 As a confirmation was this observed on a non-Windows platform? I am occasionally still getting the following on macOS, but have no issues on Windows. I will need to debug further I think.

```
Initialization for self-contained components is not supported
FAILURE: Type: 1, Error code: 80008093
Abort trap: 6
```

**Comment by AaronRobinsonMSFT** [comment]
Found it. There was another bug I had introduced when indicating how much of the buffer I had used.

https://github.com/AaronRobinsonMSFT/DNNE/blob/449e4cc45ca79ceac477684cbd0cca7a275592e6/src/platform/platform.c#L235

The above should really be the buffer consumed not its length. This bug isn't in the Windows version.

**Comment by alberts2** [comment]
> @alberts2 As a confirmation was this observed on a non-Windows platform? I am occasionally still getting the following on macOS, but have no issues on Windows. I will need to debug further I think.
> Initialization for self-contained components is not supported
> FAILURE: Type: 1, Error code: 80008093
> Abort trap: 6

On windows it only worked if it was run from somewhere on `C:` and it didn't work if it was placed on another volume like `G:`

**Comment by AaronRobinsonMSFT** [comment]
@alberts2 Okay. I will verify that scenario as well. There were at least 2 issues here and I have addressed both. The updated package has been published - https://www.nuget.org/packages/DNNE.
