### ISSUE TITLE
[Question] How to Consume The Libraries

### ISSUE THREAD

**Issue by jamsoft** [AaronRobinsonMSFT/DNNE#132]
This is a really interesting project, thanks.

Although I must admit I'm a little lost. I've picked up a project that has made use of this to compile a native dll (windows at the moment). This is all working brilliantly. The native dll is a plugin for an application. When I add the plugin it's all working perfectly.

The plugin provides a way for my application to talk to the application hosting my plugin. The issue for me is I'm not clear on how to actually consume these libraries.

My application is also AOT compiled .NET6.0 application so it's naturally expecting all dependencies to be local to the main .exe but these dlls have to be in the directory structure of the host application.

Really not sure how to proceed.

**Comment by AaronRobinsonMSFT** [comment]
@jamsoft Were you able to get unblock? I don't fully understand your scenario actually. DNNE does have experimental support for a self-contained deployment, but it is a manual process.

https://github.com/AaronRobinsonMSFT/DNNE/blob/c2feaa898fe35587f6e5f692809dac05ce44e856/src/msbuild/DNNE.props#L87-L93

As far as AOT, if that is a path your application works with, I would AOT your plugin as well and not use DNNE at all. Dotnet's NativeAOT solution can produce a shared library or an executable binary if desired.
