### ISSUE TITLE
License MIT (?)

### ISSUE THREAD

**Issue by climblinne** [AaronRobinsonMSFT/DNNE#134]
Hello,
there is no offical license file in the repository. It would be nice to activate it in GitHub. 
I found the "MIT" license inside the project file.

**Comment by AaronRobinsonMSFT** [comment]
@climblinne I'm very ignorant in how to properly define licenses for a repo. Is the correct way to have one at the root of the repo as opposed to banners in source?

**Comment by AaronRobinsonMSFT** [comment]
Done https://github.com/AaronRobinsonMSFT/DNNE/commit/236974815bbefd80d844d9c38f8fb154df33684b
