### ISSUE TITLE
I got error code -2146233079 on abort when I tried to load runtime

### ISSUE THREAD

**Issue by dayo05** [AaronRobinsonMSFT/DNNE#138]
Thanks for wonderful API for calling managed code from native code.
I'm trying to use C# with Java with JNI, DNNE.
So, I made some wrapper code for that:
```cpp
#include "library.h"

JNIEXPORT void JNICALL Java_me_ddayo_minecraftchangaeyeon_JNI_dotnetInit() {
    dotnet_init();
}
```
And also, I made some managed C# code like this:
```cs
using System.Runtime.InteropServices;

namespace DNNELib;

public class Exported
{
    [UnmanagedCallersOnly(EntryPoint = "dotnet_init")]
    public static void Init()
    {
        
    }
}
```
dotnet_init exported fine due I'm able to compile those all.
I got exit code 6 when I call that JNI method. Maybe the wrong place will be part of DNNE because, when I remove dotnet_init(), it works excepted.
I tried to use [override.c](https://github.com/AaronRobinsonMSFT/DNNE/blob/master/test/ExportingAssembly/override.c) and I got those error code: `2, -2146233079`
I have no idea what this code means. 

Thank you!

**Comment by AaronRobinsonMSFT** [comment]
Hi @dayo05, Can you share what OS and bitness you are on? When you run on that platform, have you been able to run the sample found at https://github.com/AaronRobinsonMSFT/DNNE/tree/master/sample? That is the first thing I would confirm. The `-2146233079` is [`COR_E_INVALIDOPERATION`](https://github.com/dotnet/runtime/blob/4cbe6f99d23e04c56a89251d49de1b0f14000427/src/coreclr/pal/prebuilt/inc/corerror.h#L236). It would be helpful to know the native stack in this case as well.

**Comment by dayo05** [comment]
I'm on mac os ventura(13.1) arm64 with dotnet 6.0.
I've didn't test entire sample yet so I'll do asap and share the result.

**Comment by dayo05** [comment]
I've tried to build this and run unit test on repo.
The result is all success. I'm just try to check if this occurs on windows x64.
But, I've changed some build options because this seems not fine to build on my env.

Changed options are those:
```xml
<!-- edit dnne-pkg.csproj -->
<Import Project="$(MSBuildBinPath)\Microsoft.Common.targets" />
```

**Comment by dayo05** [comment]
@AaronRobinsonMSFT I got maybe same error on my linux x64 machine.
This is tested code: [Repo](https://github.com/dayo05/DNNE138)

**Comment by AaronRobinsonMSFT** [comment]
@dayo05 This is a fundamental issue that is failing. Can you enable tracing and see if that helps root out the issue.

`$ COREHOST_TRACE=1 ./cpp`

**Comment by AaronRobinsonMSFT** [comment]
Details on host tracing options can be found at https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md.

**Comment by AaronRobinsonMSFT** [comment]
@dayo05 It seems you are hitting https://github.com/dotnet/runtime/issues/43036. The solution here is to also link against the pthread lib at https://github.com/dayo05/DNNE138/blob/79321691b4f4ae04ccad471084f51ca3d284af49/cpp/CMakeLists.txt#L7.

That line should be updated as follows:
```diff
- link_libraries( /home/dayo/minecraftchangaeyeon/dotnet/DNNELib/DNNELib/bin/Debug/net6.0/linux-x64/libDNNELibNE.so )
+ link_libraries( /home/dayo/minecraftchangaeyeon/dotnet/DNNELib/DNNELib/bin/Debug/net6.0/linux-x64/libDNNELibNE.so pthread )
```

Please let me know if this fixes your issue so I can push on the associated issue in dotnet/runtime.

**Comment by dayo05** [comment]
> Details on host tracing options can be found at https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md.

I found what's wrong with me. In tracing, dnne tries to load `obj/Debug/net6.0/osx-arm64/dnne/bin/DNNELib.dll` but binary doesn't exists there.
I've tested with remove of pthread linking in `CMakeLists.txt` also, it works fine when I manually copy the managed library to that path. 

Thanks for your attention.

**Comment by apekros** [comment]
Is there any steps to resolve this without linking the native exporting library directly?

**Comment by AaronRobinsonMSFT** [comment]
@apekros I don't think so, but that could be based on what runtime is being targeted. Are you targeting 5, 6 or 7?
