### ISSUE TITLE
Is this project the same as dotNet 7 Native OAT?

### ISSUE THREAD

**Issue by ThaDaVos** [AaronRobinsonMSFT/DNNE#142]
I noticed it's using the same namespace for the Attribute and such - so was curious, is this implemented in dotNet 7? Or is dotNet 7's implementation based on this?

**Comment by AaronRobinsonMSFT** [comment]
@ThaDaVos I alluded to this in the [`readme.md`](https://github.com/AaronRobinsonMSFT/DNNE#native-exports-for-net) by mentioning CoreRT. The CoreRT project is where NativeAOT came from. This project was inspired by CoreRT and decided to use the same attribute, [`UnmanagedCallersOnly`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute), to express the same concept. NativeAOT is different from DNNE in that it converts the managed portion to actual native code. DNNE is similar in that it exposes a native entry point but retains the managed code as emitted by Roslyn. This has benefits and limitations. A benefit is the library isn't limited by [NativeAOT constraints](https://learn.microsoft.com/dotnet/core/deploying/native-aot/#limitations-of-native-aot-deployment). The counter here is that DNNE is limited to the normal constraints of the .NET runtime, such as not supporting multiple instances of the runtime in the same process.
