### ISSUE TITLE
Export static variable entry points

### ISSUE THREAD

**Issue by tonyvfish** [AaronRobinsonMSFT/DNNE#146]
Hello I am looking at working with the new CLAP audio plugin and its export definition is CLAP_EXPORT extern const clap_plugin_entry_t clap_entry;
A static variable and not a function
Is it possible in someway to do this from managed code, export a static variable and not a function ?

https://github.com/git-moss/clap-tutorials/blob/main/src/moss-main.c see line 347

**Edit - direct reference**
https://github.com/git-moss/clap-tutorials/blob/53c4f72b9b3d3c4acdbe7e35774fe186042db46d/src/moss-main.c#L347-L352

**Comment by AaronRobinsonMSFT** [comment]
@tonyvfish Unfortunately no there isn't, at least at present. This has been a request though previously, perhaps @jkotas recalls where. DNNE does support including additional translation units (that is, C files). It would be entirely possible to have that included in the final binary but would need to be written in C.

I believe [NativeAOT](https://learn.microsoft.com/dotnet/core/deploying/native-aot/) supports this, but that is also something that I would defer to @jkotas.

Regardless, if anyone has a suggestion on how this might work I am more than willing to add support.

**Comment by jkotas** [comment]
NativeAOT does not support this either.

Including additional C file is the only way to do this.

**Comment by tonyvfish** [comment]
Thank you Aaron
