### ISSUE TITLE
Assembly resolution differences

### ISSUE THREAD

**Issue by mterwoord** [AaronRobinsonMSFT/DNNE#154]
I have legacy Delphi 6 application, which is extended by some .NET Framework 4.8 modules, by using the nuget package DllExport. That project basically works the same as this one.

I'm trying to move these .NET modules to .net 7, using DNNE. I'm really, really close. I run into behavioral differences in Assembly.Load.
The .NET modules use devexpress using WPF for UI. At some point, WPF is trying to load a given fully qualified type. This fails on code running using DNNE, but succeeds when running in a standalone .net 7 project. I recompiled WPF, and putting a breakpoint on the spot where it fails, and faking the load using the debugger, everything works like a charm. This suggests to me that it's not a problem of missing dependencies.

Are there any known differences in the host this project makes and the default executable host?

I'm not sure if the above makes sense or not. Please let me know what I can do to get this issue diagnosed.

**Comment by AaronRobinsonMSFT** [comment]
> I'm not sure if the above makes sense or not. Please let me know what I can do to get this issue diagnosed.

I get the fact that there are behavioral differences, but the precise issue being faced is difficult for me to fully understand. My first instinct would be to use [`fuslogvw.exe`](https://learn.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) to help narrow down how they are being loaded for .NET Framework and then use [`dotnet-trace`](https://learn.microsoft.com/dotnet/core/dependency-loading/collect-details) to understand what is going on in .NET 7.

> Are there any known differences in the host this project makes and the default executable host?

I assume this i referring to a process where .NET 7 is hosted. Yes, DNNE loads the assembly into it's down Assembly Load Context. This is the current design of the .NET hosting API, although a [new option is being added in .NET 8](https://github.com/dotnet/runtime/issues/77696).

**Comment by AaronRobinsonMSFT** [comment]
> The differences I mean is settings between a "normal" .net 7 wpf application, and the situation where the Delphi6 process loads .net 7 with DNNE.

Ah. Yes, there are fundamental differences between the two. The first is that I don't think the WPF workload is going to be included in the TPA, so referencing any WPF assemblies is going to be tough without using a custom [`AssemblyLoadContext`](https://learn.microsoft.com/dotnet/core/dependency-loading/understanding-assemblyloadcontext) to help find the WPF assemblies. This will also need to help find Devexpress assemblies unless they are adjacent to the exporting managed assembly.

The [`dotnet-trace`](https://learn.microsoft.com/dotnet/core/dependency-loading/collect-details) tool mentioned above will help sort out where assemblies are being looked for and what the custom `AssemblyLoadContext` will need to do in order to find the other assemblies.

**Comment by mterwoord** [comment]
I will do further digging with dotnet-trace, although it seems all dll's are loaded fine.

**Comment by AaronRobinsonMSFT** [comment]
> but can you give me any pointers where to start looking for host configuration differences?

@mterwoord I'm relatively sure the logic I mentioned above is the culprit - the lack of WPF assemblies in the TPA. The entry point for coreclr initialization is [here](https://github.com/dotnet/runtime/blob/ff109993bdd05fc653d09a266cc813dfed009504/src/coreclr/dlls/mscoree/exports.cpp#L238-L261), but starts in DNNE from [here](https://github.com/AaronRobinsonMSFT/DNNE/blob/668118e9d0f859efd4437bb763b3bac9decabe0f/src/platform/platform.c#L449). For a normal WPF application many more properties are filled out by reading the `.runtimeconfig.json` file and passing it down.

Were you able to collect a trace? Stepping through the apphost start up for a WPF application is interesting from an academic exercise, but I'm not convinced that is worth the effort. Please let me know if you were having trouble collecting the traces. Recall that DNNE loads its assembly in a seperate ALC so handling ALCs for DNNE is likely to be a requirement regardless of how the runtime is initialized.

Perhaps @elinor-fung has another avenue of investigation or thoughts.

**Comment by elinor-fung** [comment]
> the lack of WPF assemblies in the TPA

If your library [references the .NET Desktop SDK](https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props-desktop#net-5-and-later-versions), the generated `.runtimeconfig.json` should include the corresponding framework (`Microsoft.WindowsDesktop.App`) such that WPF assemblies will be in the TPA.

The trace would be helpful to see what is actually going on. Like @AaronRobinsonMSFT, I expect this is ALC-related - even though the DLLs are loaded fine, they may not be in the ALC your code is expecting.

Other thoughts:
- Does loading `DevExpress.Xpf.Core.WpfSvgPalette` explicitly work?
- [`AssemblyLoadContext.GetLoadContext`](https://learn.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.getloadcontext) tells you which ALC contains the specified `Assembly` instance, so you can check if your types are coming from different ALCs
- Reflection APIs like the two in your repro [infer the active ALC](https://learn.microsoft.com/dotnet/core/dependency-loading/loading-managed#when-are-managed-assemblies-loaded) when resolving types and assemblies. You can [explicitly set the reflection context](https://learn.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.entercontextualreflection) that will be used.

**Comment by mterwoord** [comment]
Did some digging.
The `.runtimeconfig.json` references the Desktop SDK.
What I found out before, but it's being confirmed by a `dotnet-trace` run, is that my code (exported method by DNNE) starts off in an "IsolatedComponentLoadContext", and somehow, at some point, it's also utilizing the `Default` context. The situation where I get issues shows that somehow the code is running from the Default context instead of the IsolatedComponentLoadCOntext.

Is there any way to get stack traces of the loader events i'm looking for? Ie, find out where the transition is being made?

Other option would be to somehow get rid of the IsolatedComponentLoadContext and only have 1 ALC, which is also the default one.

**Comment by mterwoord** [comment]
I did some further digging. It seems that some DevExpress module initializer triggers code into the Default ALC.
I now tricked my main entrypoint in giving control to the Default ALC, and then everytrhing works. I will close this ticket now. I'm happy to give more insights if needed/wanted by anyone.
