### ISSUE TITLE
DocFx: error : Generated source file(s) .... not found

### ISSUE THREAD

**Issue by tvogel-nid** [AaronRobinsonMSFT/DNNE#159]
I'm actually run DocFx over a couple of projects and one of them uses DNNE to generate and build native libs.
I use the way [DocFx from csproj](https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#generate-from-projects-or-solutions) and from the description I read that 

> When the file extension is .csproj, .vbproj or .sln, docfx uses [MSBuildWorkspace](https://gist.github.com/DustinCampbell/32cd69d04ea1c08a16ae5c4cd21dd3a3) to perform a design-time build of the projects before generating API docs.

If I understand the DNNE.targets file correctly than the target:
```
<Target
    Name="DnneGenerateNativeExports"
    Condition="('$(DesignTimeBuild)' != 'true' OR '$(BuildingProject)' == 'true') AND '$(DnneSupportedTFM)' == 'true' AND '$(DnneBuildExports)' == 'true'"
```
checks for DesignTimeBuild and doesn't create the NativeExports, the following 
```
  <Target
    Name="DnneBuildNativeExports"
    Condition="'$(DnneBuildExports)' == 'true'"
```

only checks for DnneBuildExports and therefor fails the copy step.

So I'd like to ask whether the check for DesignTimeBuild  can be added here as well?

Thanks a lot
Thomas

**Comment by AaronRobinsonMSFT** [comment]
@tvogel-nid Yep. That was done in https://github.com/AaronRobinsonMSFT/DNNE/pull/158. Updating to 2.0.1 will get you those changes.
