### ISSUE TITLE
[ReMark] Do not use spaces in project name

### ISSUE THREAD

**Issue by ThaDaVos** [AaronRobinsonMSFT/DNNE#160]
I noticed DNNE fails to generate the required source files for compilation if there are spaces inside the project name

**Comment by AaronRobinsonMSFT** [comment]
@ThaDaVos Is this something you think should be supported?

**Comment by ThaDaVos** [comment]
Not really - it could if it's useful - but maybe a note in the ReadMe could help people - as you don't get a clear error about it

**Comment by AaronRobinsonMSFT** [comment]
Sounds good. I will update the doc. If users find utility I can add support.

**Comment by ThaDaVos** [comment]
I'll close the issue - please respond to this issue if you need the support
