### ISSUE TITLE
Tutorial for dummies 

### ISSUE THREAD

**Issue by DennisGundersen** [AaronRobinsonMSFT/DNNE#161]
Could someone please write a tutorial for dummies who can hopefully use DNNE, but don't know enough to configure and compile it?

I'm an amateur programmer, but I'd like to use DNNE in a x32 project (exporting C# functions to MetaTrader 4). I understand that I need to recompile the GitHub project code rather than using the NuGet package as it's x64, but I can't figure out how compilation is done, and I'm pretty sure this stuff is beyond many other potential users of DNNE as well. 

I had great hope when I saw a Visual Studio template was posted, but to me it looks like it just creates an empty class library and sets the target to x86. There is no trace of DNNE that I can find. In any case, a tutorial would be nice for future versions and other changes.
I tried starting one, but only got this far (even with guesstimations)...

01. Download DNNE Master project from https://github.com/AaronRobinsonMSFT/DNNE.
02. Download and install the x86 version of the wanted .NET platform (here 7.0) from https://dotnet.microsoft.com/en-us/download.
03. Create an empty C# class library and change project properties; Target framework: 7.0, Target OS: Windows, Platform target: X86
04. Copy DNNE Master source code in d: (as an example)
05. Go to "D:\DNNE-master\src\msbuild" and open file "DNNE.props" 
06. Set "DnneRuntimeIdentifier" to "win-x86"
07. Open a Terminal prompt and go to "D:\DNNE-master\src"
08. Run "dotnet build create_package.proj"
09. Open "D:\DNNE-master\src\dnne-pkg\bin\Release" and copy "DNNE.2.0.1.nupkg"
10. (Only need to do this once:) In Visual Studio: Tools, Options, NuGet Package Manager, Package Sources, Add (+), Name: Local packages, Source: "D:/Downloads"
11. Paste the file "DNNE.2.0.1.nupkg" into "D:/Downloads"
12. Go to your Project in Solution Explorer, right click and select "Manage NuGet Packages". Select package source "Local packages".
13. Install DNNE.
14. Add new class with code from "D:\DNNE-master\sample"
15. Collect underpants
16. Yeah, I've got nothing (as this still won't work due to missing "hostfxr" and more x86 vs x64 stuff).
17. Get rich and famous.

Re
Dennis

PS! Of course I've read the Readme file, but that stuff is not really written for amateurs...

**Comment by DennisGundersen** [comment]
`namespace ClassLibrary1
{
    public class Exports
    {
        [UnmanagedCallersOnly(EntryPoint = "FancyName")]
        public static int MyExport(int a)
        {
            return a;
        }
    }
}`

**Comment by ThaDaVos** [comment]
Please see my comment on another issue - I created a template for x86 based projects - like mentioned there, you can just use the latest DNNE nuget package:
https://github.com/AaronRobinsonMSFT/DNNE/issues/157#issuecomment-1473884062

**Comment by DennisGundersen** [comment]
Okay... I thought the template used a local compiled DNNE version on your machine as I couldn't see anything about it, but yes, adding the normal NuGet package to my library created by this template it does indeed compile. I'm happy, but at the same time feel like I understand even less now...
Is <PropertyGroup Label="DNNE"...> in .csproj the only thing it took? How can that be if the NuGet is x64?

Re
Dennis

**Comment by ThaDaVos** [comment]
Just take it from me - NuGet does have some magic regarding that subject - it knows what to get for your specific runtime.

To answer your questions:

> Is <PropertyGroup Label="DNNE"...> in .csproj the only thing it took?
Yes it was, as it's the way to reference NuGet packages

> How can that be if the NuGet is x64?
You're talking about the NuGet binary? If so, does it really matter that it's a x64 binary? Bet you're using a 64x Visual Studio too, and a 64x Windows and probably a 64x browser - there are ways to go from x86 to x64 and back - the only thing NuGet is responsible for is getting the right assembly for you during/before compilation - as your project is targeting x86 - it will get the x86 assemblies and vice-versa

Just FYI - NuGet isn't part of your project, it's a development tool you use

**Comment by DennisGundersen** [comment]
I'm planning on connecting MetaTrader 4 to my C# library, and I know from my old solution (.NET Framework 4.x using Robert Giesecke's DLLExport) that is has to be x86, not Any CPU, and Aaron mentioned in that other post that the official NuGet was x64. MT4 is finicky as all heck and seem to have only one error code (basically "FU"). Not very helpful.
I'd still love to know how to actually compile DNNE and how this template works as I've spent a couple of weeks on it already, but I guess I'm not in a hurry since I still have to find out how to connect the rest.

So, thank you very much!

Re 
Dennis

**Comment by DennisGundersen** [comment]
One more question (sorry). The template seems to dump out a whole lot of files, maybe the whole .NET framework. Is that really necessary if the correct .NET framework is already installed on the machine?

**Comment by DennisGundersen** [comment]
Oh, yeah. Don't know how to use the resulting files yet, but that looks much better. I'll try to update the template for this version. By the way, if I can make this work with Metatrader I really should share the solution with that crowd. Would that be a problem for you?

**Comment by AaronRobinsonMSFT** [comment]
@DennisGundersen Were the [notes](https://github.com/AaronRobinsonMSFT/DNNE#generating-a-native-binary-using-the-dnne-nupkg) in the readme not helpful? You likely are missing the Runtime Identifier (RID) for x86.

**Comment by AaronRobinsonMSFT** [comment]
Also, the [`sample\`](https://github.com/AaronRobinsonMSFT/DNNE/tree/master/sample) should be loadable in Visual Studio if desired. It doesn't include a native project for consuming it in the solution. However, in the `sample/native` directory there is a `main.c` that shows an example of consuming from native code.

**Comment by ThaDaVos** [comment]
> Oh, yeah. Don't know how to use the resulting files yet, but that looks much better. I'll try to update the template for this version. By the way, if I can make this work with Metatrader I really should share the solution with that crowd. Would that be a problem for you?

You mean my template? Of course not - share it if you want - i created it to be shared and cause I have multiple projects to create the same way

**Comment by DennisGundersen** [comment]
> @DennisGundersen Were the [notes](https://github.com/AaronRobinsonMSFT/DNNE#generating-a-native-binary-using-the-dnne-nupkg) in the readme not helpful? You likely are missing the Runtime Identifier (RID) for x86.

With all due respect, I believe you are assuming way to much knowledge on the part of the readers and thereby excluding the majority of your potential users. I'm a forms-over-data dabbler (that gets nightmares remembering the c++ classes in uni even after 35+ years), but who can certainly massage lists of data in C# well enough to do auto trading in Forex as long as the InterOp bridge is set up by someone else. My guess is that there are massive amounts of hobbyists on my level that would love DNNE if they knew of it, and had a simple enough tutorial to get the plumbing done automagically without ending up like Underpants Gnomes (Southpark joke).

Something like this (not done yet):

01 Download and place the VS template package ClassLibraryforMT4WithDNNE.zip in \Visual Studio 2022\Templates\ProjectTemplates
02 Open VS, Create new project using the template (search for DNNE and look at the bottom)
03 Install DNNE from NuGet
04 Write your code
05 Publish project to folder, and make sure Deployment mode = Framework-dependent (More actions, Edit)
06 There should be two dll's, two header, and two json files in the publish folder.
07 As I understand it the ProjectNameNE.dll is the one with DNNE included.
08 sample/native/main.c shows how to call the file from c++
09 sample/mt4/sampleEA.mql coming soon
[ClassLibraryforMT4WithDNNE.zip](https://github.com/AaronRobinsonMSFT/DNNE/files/11048142/ClassLibraryforMT4WithDNNE.zip)

Re
Dennis

**Comment by DennisGundersen** [comment]
> > Oh, yeah. Don't know how to use the resulting files yet, but that looks much better. I'll try to update the template for this version. By the way, if I can make this work with Metatrader I really should share the solution with that crowd. Would that be a problem for you?
> 
> You mean my template? Of course not - share it if you want - i created it to be shared and cause I have multiple projects to create the same way

Excellent. I've got a friend of mine who actually likes c++ looking at what I've got so far, and assuming we can make an automagic solution for dummies useable in MT4 I will post it on mql5.com (the forums for MetaTrader). I'll keep eveyone's names in for credit, but try to keep the setup so simple that this place won't get flooded (there are looooots of Forex traders hoping to live a work free life of leisure and riches).

**Comment by AaronRobinsonMSFT** [comment]
> I believe you are assuming way to much knowledge on the part of the readers and thereby excluding the majority of your potential users.

I don't understand this statement. The example under `sample/` does just that. Load it in VS and it produces a .NET assembly and native export without issue. The issue it seems has nothing to do with DNNE on x64 but rather DNNE when targeting x86 as x64, the default arch for .NET, works precisely as described.

I genuinely want to help here but I'm confused as to the underlying issue. Using NuGet package manager in Visual Studio to add DNNE to an existing .NET project and then marking a function with `UnmanagedCallersOnly` is about as easy as it gets. The tricky part is when targeting x86 as opposed to x64, which I agree can be annoyingly difficult.

> 07 As I understand it the ProjectNameNE.dll is the one with DNNE included.

Yes, but can be overridden using MSBuild properties - see all available options in [`DNNE.props`](https://github.com/AaronRobinsonMSFT/DNNE/blob/master/src/msbuild/DNNE.props).

**Comment by AaronRobinsonMSFT** [comment]
> Still not sure where to put variables, but try a bunch of stuff and get so into it that I don't even pick up that the posted template solves my problem. When ThaDaVos told me all the "DNNE.props" just go in the .csproj file and then you can use the regular NuGet package, you could have floored me with a feather.

Ah. I can absolutely fix that.

> so a quick "To use DNNE as x86, slap this XML code into your project file" post, should help.

Excellent suggestion. I can make a clearer example for that.

Thank you for pointing out this confusion.

**Comment by AaronRobinsonMSFT** [comment]
@DennisGundersen I've updated the readme to clarify some of the confusion that people have faced. I've added more comments and examples of properties to the Sample project and hopefully reworked the readme to be more intuitive to follow. Please let me know if you think there are more things that can be done.

**Comment by DennisGundersen** [comment]
> @DennisGundersen I've updated the readme to clarify some of the confusion that people have faced. I've added more comments and examples of properties to the Sample project and hopefully reworked the readme to be more intuitive to follow. Please let me know if you think there are more things that can be done.

Looks good to me, (now that I realize the connection between DNNE.props and .csproj, but that was probably just a blind spot on my side, not a regular thing).

Thank you very much for the help.

Re
Dennis
