### ISSUE TITLE
Can the file be separated

### ISSUE THREAD

**Issue by BoneTM** [AaronRobinsonMSFT/DNNE#166]
Don't want to put native code and dotnetcore in the same directory, can i move the dotnetcore to any other folder?

**Comment by AaronRobinsonMSFT** [comment]
> Don't want to put native code and dotnetcore in the same directory,

Which file? The resulting native binary with exports or the generated `.c` file? At present there is no way to separate the two as they are technically bound to one another with the generated `.runtimeconfig.json` file. Can you share some more details on why this is needed or the possible confusion it is creating?

**Comment by BoneTM** [comment]
thanks for answering.

1st, there is a dotnet core project with dnne name `Program.dll`, after publish, there will be a `ProgramNE.dll` file.
2nd, i make a c++ project name `wtf.dll` which will link `ProgramNE.dll`

is it possible to make the folder structure like:

folder `extensions` with file `wtf.dll`
folder `nethost` with `ProgramNE.dll` and `Program.dll`

**Comment by BoneTM** [comment]
can `wtf.dll` load the nethost folder ?

**Comment by AaronRobinsonMSFT** [comment]
@BoneTM That is far more about MSBuild, .NET layout and OS loader than DNNE specifically.

> can wtf.dll load from other folder like nethost?

Yes, that is possible, but you will need to update your path and ensure the loader can find the binary.

>  but i need to create many stuff to get_export and redeclare the func type,
can i just link it into the wtf.dll

Not at present. DNNE doesn't provide a static build option.
