### ISSUE TITLE
How to call C++ method from C#?

### ISSUE THREAD

**Issue by dayo05** [AaronRobinsonMSFT/DNNE#167]
It looks great when calling C# from C++. But in opposite direction, it not works fine.
I thought about using DllImport attribute but I have no idea what is name of dll.
Any method about that?

**Comment by ThaDaVos** [comment]
Do you want to call a method from the generated dll? So the `{AssemblyName}NE.dll`?

**Comment by dayo05** [comment]
No, But the method which I prefer to call exactly loaded into one process.

**Comment by ThaDaVos** [comment]
You need to know the name of the DLL if you want to import a method from it - else it cannot be done.

What method are you looking for? And where is it coming from?

**Comment by dayo05** [comment]
I found dotnet/runtime#7267 ; Thanks for your attention :D
