### ISSUE TITLE
Use source generator to generate attributes

### ISSUE THREAD

**Issue by JeremyAnsel** [AaronRobinsonMSFT/DNNE#168]
Hello,
I have an idea.

To use the `DNNE.ExportAttribute`, `DNNE.C99TypeAttribute`, or `DNNE.C99DeclCodeAttribute` attribute, you have to manually add them to your project as shown in `test/ExportingAssembly/Dnne.Attributes.cs`.
Instead of manually add them, I suggest to include a source generator to generate the attributes.

Something like that:
`.csproj` class library project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.5.0" />
  </ItemGroup>

</Project>
```
`AttributesGenerator.cs` file:
```cs
using Microsoft.CodeAnalysis;

namespace DnneAttributesGenerator
{
    [Generator]
    public class AttributesGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            string source =
@"
using System;

namespace DNNE
{
    internal class ExportAttribute : System.Attribute
    {
        public ExportAttribute() { }
        public string EntryPoint { get; set; }
    }

    internal class C99TypeAttribute : System.Attribute
    {
        public C99TypeAttribute(string code) { }
    }

    internal class C99DeclCodeAttribute : System.Attribute
    {
        public C99DeclCodeAttribute(string code) { }
    }
}
";

            context.AddSource(nameof(AttributesGenerator), source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
```

You can reference the project with:
```xml
  <ItemGroup>
    <ProjectReference Include="..\DnneAttributesGenerator\DnneAttributesGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
```

The documentation to add the source generator to a NuGet package is here:
[Package a generator as a NuGet package](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#package-a-generator-as-a-nuget-package)

**Comment by AaronRobinsonMSFT** [comment]
>  I suggest to include a source generator to generate the attributes.

I am familiar with source generators. I'm not really inclined to do that though. The biggest reason is source generators should be used to respond specifically to user edits, not just inject basic types. A source generator seems like a rather big hammer for something as small as adding a few types.

**Comment by AaronRobinsonMSFT** [comment]
Looks like there might be a more light weight approach to this using the incremental source generators - [`RegisterPostInitializationOutput`](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#outputting-values). I'll try to get to this as it might be helpful for others.

**Comment by AaronRobinsonMSFT** [comment]
@JeremyAnsel Thanks to @Sergio0694, a source generator now exists in https://www.nuget.org/packages/DNNE/2.0.6

**Comment by ThaDaVos** [comment]
Funny thing - already did this with my fork too 🤣🤣
