### ISSUE TITLE
How to build x86?

### ISSUE THREAD

**Issue by ghost** [AaronRobinsonMSFT/DNNE#186]
I downloaded the [sample](https://github.com/AaronRobinsonMSFT/DNNE/tree/master/sample) and tried to build it for x86:

![Unbenannt](https://github.com/AaronRobinsonMSFT/DNNE/assets/146413885/0a772ac3-6089-4b90-949e-73de2bb78edf)

Unfortunately, this failed with the error code `2`.

    "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x86\cl.exe"
    /Od /LDd /TC /MT /GS /Zi /D DNNE_ASSEMBLY_NAME=Sample /D DNNE_COMPILE_AS_SOURCE
    /I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include"
    /I "C:\Users\Nils\.nuget\packages\dnne\2.0.1\tools\platform"
    /I "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\8.0.0\runtimes\win-x64\native"
    /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared"
    /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um"
    /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt"
    "C:\Users\Nils\Desktop\Neuer Ordner\obj\x86\Debug\net6.0\dnne\Sample.g.c"
    "C:\Users\Nils\.nuget\packages\dnne\2.0.1\tools\platform\platform.c"
    /link /DLL /LIBPATH:"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x86"
    /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x86"
    /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x86"
    "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\8.0.0\runtimes\win-x64\native\libnethost.lib"
    Advapi32.lib /IGNORE:4099
    /IMPLIB:"C:\Users\Nils\Desktop\Neuer Ordner\obj\x86\Debug\net6.0\dnne\bin\sample_native.lib"
    /OUT:"C:\Users\Nils\Desktop\Neuer Ordner\obj\x86\Debug\net6.0\dnne\bin\sample_native.dll"

The solution explorer shows an information icon for this project:
![2](https://github.com/AaronRobinsonMSFT/DNNE/assets/146413885/854dc199-9bca-4ce1-8663-4159fca9b6d1)

Is there a way for me to use DNNE for x86 only?

**Comment by AaronRobinsonMSFT** [comment]
Please share the complete output from Visual Studio, not just the error code.

What version of Visual Studio is being used?
