### ISSUE TITLE
Using DNNE.C99Type for enum does compile under windows but not linux

### ISSUE THREAD

**Issue by mkrmasch** [AaronRobinsonMSFT/DNNE#188]
I currently do not have an idea why this works on windows but not in Linux.

If I defined a method parameter: 
```
[UnmanagedCallersOnly]
 public static int FunctionCall([DNNE.C99Type("enum EnumTypeDefinition")] EnumTypeDefinition sparDefinition)
```
I defined the C99Type like this:
```
internal sealed class C99TypeAttribute : System.Attribute
{
    public C99TypeAttribute(string code) { }
}


```

it compiles with Windows but with Linux I get: 
error G13FECB51: variable has incomplete type 'enum  EnumTypeDefinition'

A workaround would be not to use the type but integers of course but is a bit less readable

**Comment by mkrmasch** [comment]
ok, I think I found the problem. There was a missing declaration. still I wonder why windows allows that.
`[DNNE.C99DeclCode(@"
    #include <stdbool.h>
    enum EnumTypeDefinition
    {
        item1,
       item2
    };
    ")]`

**Comment by AaronRobinsonMSFT** [comment]
> still I wonder why windows allows that.

The issue here is MSVC considers the type to be forward declared at this point. Dropping the `enum` gets the error you are looking for. This relates to MSVC and its tenuous adherence to C99.

https://godbolt.org/z/9bPbvqxz8
