### ISSUE TITLE
[FeatureRequest] Calling .NET6 library from a .NET8 application with DNNE built native dll in between

### ISSUE THREAD

**Issue by KalashKhator** [AaronRobinsonMSFT/DNNE#191]
I have an issue when my managed application on .NET8 is trying to call a managed library on .NET6 through some native code in between, which should be working.
But the problem here is that the native DLL that I build for my .NET6 library using DNNE, during runtime tries to blindly load .NET 6 runtime because that is what is specified in the runtimeconfig.json of the managed library. 
Is there a way where we can check if there is a [higher? maybe] version on runtime already loaded and not try to load the runtime from the generated native library?

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by AaronRobinsonMSFT** [comment]
@KalashKhator 

> Is there a way where we can check if there is a [higher? maybe] version on runtime already loaded and not try to load the runtime from the generated native library?

Yes. It is the same as for any .NET application. The mechanism is to explicit override the default [roll forward behavior](https://learn.microsoft.com/dotnet/core/versions/selection#control-roll-forward-behavior), "LatestMinor". The most appropriate for your scenario is likely "LatestMajor".

> during runtime tries to blindly load .NET 6 runtime because that is what is specified in the runtimeconfig.json of the managed library.

A minor nit with this. It isn't "blindly" doing anything of the sort. It is doing precisely what was asked of it. .NET Core activation is very prescriptive in this sense. Applications do the same thing. If an application targets .NET 6 and only .NET 8 is installed, it will fail as it is requiring .NET 6 in the same manner that DNNE is enforcing the requirement.
