### ISSUE TITLE
Add Native AOT deployment

### ISSUE THREAD

**Issue by climblinne** [AaronRobinsonMSFT/DNNE#192]
Hello,

with .NET 8.0/9.0 the Native AOT deployment seems to work quite fine. 
I would like to use it, because we have an "old" c-application, which uses multiple Native Export libraries (generated by DNNE).
Unluckily some are still based on .NET 5.0. Now my driver library updated to .NET 6.0 and the system crashes, because two version of .NET framework are not allowed.
When I use for my library the Native AOT deployment it works fine.

As I see, the export with

```XML
<PropertyGroup>
    <PublishAot>true</PublishAot>
</PropertyGroup>
```
works fine. Build automatically a lib file. Now only the header file is missing. 
And this would be great, to just take it from DNNE.

So my idea would be to recognize the "PublishAOT" flag and generate the header file as usual (may be without the "SOURCE" part and file name without "NE").

Good idea? Regards Jan

**Comment by AaronRobinsonMSFT** [comment]
@climblinne This isn't unreasonable. Other people have also asked for something similar - @Sergio0694.

It looks like there is a bug in the props with `DnneGenerateExports` and `DnneBuildExports`. My intent with `DnneBuildExports` was to be able to set to `false` and perform the scenario you describe. I don't think triggering off of `PublishAOT` is a good idea and so it isn't something I'm inclined to implement. However, your properties should be free to set `DnneBuildExports` to `false` and get the desired output.

As I mentioned there is currently a bug that I need to fix, but I should be able to put out a new package this week.

**Comment by AaronRobinsonMSFT** [comment]
@climblinne Updated - https://www.nuget.org/packages/DNNE/2.0.7

Set `<DnneBuildExports>false</DnneBuildExports>` in your `.csproj` to generated a header file, but not build.
