### ISSUE TITLE
Add support for ARM and ARM64 on Linux

### ISSUE THREAD

**Issue by pkingwsd** [AaronRobinsonMSFT/DNNE#28]
our company has some algorithm write by .net core ML.NET.
the algorithm about image process.

Now, we want run it on android. 
so we need export interface for Java(android).

**Comment by AaronRobinsonMSFT** [comment]
@pkingwsd Thanks for the suggestion. I will look into this soon.

FYI @richlander

**Comment by AaronRobinsonMSFT** [comment]
@pkingwsd May I assume you are building on an ARM or ARM64 platform when compiled for those platforms?

**Comment by pkingwsd** [comment]
just ARM64  @AaronRobinsonMSFT
