### ISSUE TITLE
Enable Major Rollforward for the dnne-gen tool

### ISSUE THREAD

**Issue by jkoritzinsky** [AaronRobinsonMSFT/DNNE#44]
Today if you try running DNNE with a .NET 6 SDK that does not have a .NET 5 runtime installed, DNNE will fail to run since it does not enable major roll forward. Updating the DNNE targets to enable major roll forward (with the `--roll-forward` flag) makes DNNE work correctly when there is only a .NET 6 runtime available.

**Comment by AaronRobinsonMSFT** [comment]
This seems like a reasonable feature. Creating a new MSBuild property to indicate this flag should be passed would be how to fix this.

https://github.com/AaronRobinsonMSFT/DNNE/blob/70f147d56a1d4d71aa9d9d945c26f654c872a0fd/src/msbuild/DNNE.targets#L36

**Comment by AaronRobinsonMSFT** [comment]
The roll forward policy can now be controlled through the `DnneGenRollForward` MSBuild property. See `dotnet` help to determine supported values.
