### ISSUE TITLE
Inconsistent function exporting

### ISSUE THREAD

**Issue by sanny-io** [AaronRobinsonMSFT/DNNE#57]
When building my managed dll, sometimes the exported function names are inconsistent and cause my host program to crash when trying to load the dll.

The following dumps are from the code provided at the bottom.

This first dump does not cause my program to crash.

```
ordinal hint RVA      name

          1    0 00001444 get_hostfxr_path
          2    1 00013520 gmod13_close
          3    2 00013560 gmod13_open
          4    3 00013E80 preload_runtime
          5    4 00014200 set_failure_callback
```

Causes a crash.

```
ordinal hint RVA      name

          1    0 000012F2 _get_hostfxr_path@12 = _get_hostfxr_path@12
          4    1 0000DBC0 _preload_runtime@0 = _preload_runtime@0
          5    2 0000DEE0 _set_failure_callback@4 = _set_failure_callback@4
          2    3 0000D3B0 gmod13_close = _gmod13_close
          3    4 0000D3E0 gmod13_open = _gmod13_open
```

Also causes a crash.

```
ordinal hint RVA      name

          1    0 000012F2 _get_hostfxr_path@12
          4    1 0000DBC0 _preload_runtime@0
          5    2 0000DEE0 _set_failure_callback@4
          2    3 0000D3B0 gmod13_close
          3    4 0000D3E0 gmod13_open
```

```csharp
[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) }, EntryPoint = "gmod13_open")]
public static int Open(IntPtr state)
{
    Console.WriteLine("Hello");
    return 0;
}

[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) }, EntryPoint = "gmod13_close")]
public static int Close(IntPtr state)
{
    Console.WriteLine("Goodbye");
    return 0;
}
```

The only tinkering I did was with the configuration (Release/Debug) and target platform (x86/x64). I can't consistently get any combination of these settings to give me the first dump again.

**Comment by AaronRobinsonMSFT** [comment]
@sanny-io This sounds like a series of issues with calling conventions. The latter two outputs represent x86 calling conventions - anything with an `@N` prefix is `stdcall`. Can you elaborate on how the native binary is being consumed?

**Comment by sanny-io** [comment]
Simple `LoadLibrary` with `GetProcAddress`. But I've figured out why the program was crashing: I wasn't putting the managed dll and .json together with the native one. It's just weird that it wasn't consistent. I suspected the names weren't being properly exported, but they are. With the managed dll and .json, everything works as expected. Thank you for your help though.
