### ISSUE TITLE
Error LNK2019: unresolved external symbol _get_hostfxr_path@12 referenced in function _load_hostfxr

### ISSUE THREAD

**Issue by netcorefan1** [AaronRobinsonMSFT/DNNE#58]
Hello,
first of all I want to congratulate with the author. This is the only library that got me up and running.
Unfortunately I am experiencing (what I believe to be) the same [issue](https://github.com/AaronRobinsonMSFT/DNNE/issues/52#issue-757946234) reported here.
I am trying to build two separate x86 and x64 dll. 
x64 compiles fine, but the x86 fails with the following errors:
`Error LNK2019: unresolved external symbol _get_hostfxr_path@12 referenced in function _load_hostfxr`
Even if I export with `[UnmanagedCallersOnly(CallConvs = new []{typeof(System.Runtime.CompilerServices.CallConvCdecl)})]` it still fails with the same error.
The project is a simple .Net 5 library containing the following function:
```
[UnmanagedCallersOnly()]
public static int Run(IntPtr parameters)
{
      return 0;
}
```
I am only interested in Windows 10, but I also need x86 architecture working.
I am running the latest VS2019 with the latest Windows SDK available in its installer (19041).
May be I'm missing something obvious, but after looking the documentation for hours without understanding what I am doing wrong I have no other choice than ask for help.
Many thanks

**Comment by AaronRobinsonMSFT** [comment]
@netcorefan1 This is because of the missing x86 lib. Please ensure the x86 version of .NET 5 is installed as well - https://dotnet.microsoft.com/download/dotnet/5.0. I believe this is the same issue as https://github.com/AaronRobinsonMSFT/DNNE/issues/29.

It would be helpful to describe your workflow so I can document this. It seems this scenario is one people want but keep hitting issues with so I need to provide clearer guidance here I think.

>first of all I want to congratulate with the author. This is the only library that got me up and running.

Much appreciated.

**Comment by netcorefan1** [comment]
Oh my God! The fix was so easy and obvious! The x86 version of .Net 5 was not installed.
It's just that when someone is going to install the SDK they mostly go with the x64 thinking that it only relates to their OS architecture.
This is what I have done:
- uninstalled the old x64 (it was one build behind)
- reinstalled the x64 version (the current 102 build)
- installed the x86 version (the current 102 build)
- rebooted the system
- ensure that everything is correctly installed:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Not sure why it still finds 101. I uninstalled it! (I hope that Microsoft will make .Net 5 part of the OS soon)
- create a new sample library from scratch with the same code I previously mentioned.

The result is that x64 and AnyCPU compiles fine. As soon as I try to compile x86 I get the same error which forced me to open this issue and this happens also with `CallConvCdecl` flag.
I should also mention that, due to some internal configurations, VS is installed on a different partition (of the same HD), but I believe this should not make any difference.
I attached here the sample project.
Many thanks
[DNNE_Sample.zip](https://github.com/AaronRobinsonMSFT/DNNE/files/5896343/DNNE_Sample.zip)

**Comment by AaronRobinsonMSFT** [comment]
>I tried other configurations (which now I don't remember) in order to have parallel compilation, but I get Error C1041: cannot open program database if multiple CL.EXE write to the same .PDB file, please use /FS. This flag is not enabled in DNNE compile command and I couldn't find a way to add it (<DnneCompilerCommand>/FS</DnneCompilerCommand> just resulted in error).
For me it's enough as is since I already spent too much time, but if you have better ways to obtain the same please let me know.

Can you please file a new issue on this? The request here is for parallel building of two architectures which isn't going to be supported at present and will require some thought.

>If it is not an expensive call, may be a quick IsX86SdkInstalled ?? As is we get a cryptic error which give us no idea on the cause, but if we get an error like "X86 SDK not installed" then we already know what to do and we can solve everything in a couple of minutes (instead of hours like happened in my case).

I will see what I can do here. Thanks for the suggestion.

**Comment by esso23** [comment]
@AaronRobinsonMSFT 
I think it should be stated somewhere in the docs that you need this:
`<RuntimeIdentifier>win-x86</RuntimeIdentifier>`
for the x86 compile to work.
At first I went with just `<PlatformTarget>x86</PlatformTarget>` and the compilation failed with the mentioned error:
`1>platform.obj : error LNK2001: unresolved external symbol _get_hostfxr_path@12`

**Comment by AaronRobinsonMSFT** [comment]
@esso23 A bullet under step 3 [here](https://github.com/AaronRobinsonMSFT/DNNE#generating-a-native-binary-using-the-dnne-nupkg) mentions this. Is the MSBuild properly itself needed too?

**Comment by esso23** [comment]
@AaronRobinsonMSFT I did not notice it there, my bad.
Anyway, I was following the ExportingAssembly example from test folder in the repo and made the configuration like in here https://github.com/AaronRobinsonMSFT/DNNE/blob/master/test/ExportingAssembly/ExportingAssembly.csproj - where the RID is not explicitly specified.
Maybe adding `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` there explicitly would be good (even though it does not need to be explicitly specified) - just to prevent confusion for other people in the future.

**Comment by AaronRobinsonMSFT** [comment]
@esso23 Good suggestion. I will update the example project file with some comments on this.

**Comment by AaronRobinsonMSFT** [comment]
@esso23 Added with https://github.com/AaronRobinsonMSFT/DNNE/pull/67.
