### ISSUE TITLE
Allow the native library to be explicitly named

### ISSUE THREAD

**Issue by sanny-io** [AaronRobinsonMSFT/DNNE#59]
Not sure if this is possible, but messing with post-build events and such to rename it isn't ideal. An option to explicitly set the name instead of a suffix would be much easier for automation.

**Comment by AaronRobinsonMSFT** [comment]
@sanny-io Is the idea that more than a suffix is needed ? I assume this has more to do with the desire to name the native export binary as you want it rather than any real technical issue. Can you provide an example of how the native export binary is named vs the managed assembly?

**Comment by sanny-io** [comment]
Correct. The native export binary appends `NE` to the managed assembly's name through the `DnneNativeBinarySuffix` property. What I propose is instead a property to outright set the generated binary's name. Perhaps a new `DnneNativeBinaryName` property that defaults to `<DnneNativeBinaryName>$(TargetName)NE$(TargetExt)</DnneNativeBinaryName >`
