### ISSUE TITLE
Xamarin/.NET 6 support

### ISSUE THREAD

**Issue by gkarabin** [AaronRobinsonMSFT/DNNE#61]
I have been following this project since reading about it at https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-8/#native-exports .  I am primarily a Xamarin developer and only dabble in the greater .NET ecosystem. After rereading the blog post I noticed that your team is looking for feedback on the capability of this project.

My team develops libraries for Xamarin application builders. There is a market for these libraries in native mobile development languages (mostly On Android/Java). An interop system like this would be interesting to our team if we could export a native library (which we would then invoke via JNI, etc). We don’t need something that maps higher level language constructs - something simple for marshaling is fine as long as the management of the runtime is safe and reliable.

I don’t know if this is the sort of feedback that you were looking for or expecting, but I thought I’d pass it along. Your project looks very interesting and I look forward to experimenting with it as .NET 6 comes to fruition, whether or not supporting Xamarin targets is an immediate goal for you. Thanks!

**Comment by AaronRobinsonMSFT** [comment]
@gkarabin Thank you for reaching out.

>An interop system like this would be interesting to our team if we could export a native library (which we would then invoke via JNI, etc).

Sounds good. That description is precisely the kind of interest we want to confirm exists.

> We don’t need something that maps higher level language constructs - something simple for marshaling is fine as long as the management of the runtime is safe and reliable.

That aligns with the current DNNE goals. We defer all marshalling to be done manually by the developer. This allows focused support their needs and we impose the minimum to maintain key runtime invariants.

>Your project looks very interesting and I look forward to experimenting with it as .NET 6 comes to fruition, whether or not supporting Xamarin targets is an immediate goal for you.

There is no immediate plan to support any platform prior to .NET 5. However, it is a [stated goal to fold Xamarin into .NET 6](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) so once that occurs DNNE will "just work".

**Comment by gkarabin** [comment]
Thanks! I look forward to giving it a go once VS for Mac starts downloading .NET6 betas!
