### ISSUE TITLE
Is there a nice solution for forward Console.WriteLine from C# to C?

### ISSUE THREAD

**Issue by AlexGer123** [AaronRobinsonMSFT/DNNE#71]
Hi,

does anyone have a nice solution to forward Console.WriteLine.

Example:
If I print out an error message with Console.WriteLine in C#...can I forward the massage direct to C layer.
Or is the only way to save the massage and when an error occurs I need to call a function to get the last error string?

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 The implementation of `Console.WriteLine` will eventually go to `fprintf`. Can you elaborate on what you are trying to accomplish?

The DNNE project is primarily targeted at starting native code and calling into .NET. It sounds like you are starting in .NET and calling into native code.

**Comment by AlexGer123** [comment]
I have written a parsing module in C#. I call this module from C layer.
If an error happend in this module, I want to print out (forward) the error massage C layer too.

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 Thank you, that does help. In this case I would suggest having a "global error reporting callback" or take a callback on each export. For example,

```csharp
// Callback can be byte* or ushort* depending on what encoding is being used.
private static delegate* unmanaged<byte*, void> s_Callback;
[UnmanagedCallersOnly]
public static void SetErrorMessageCallback(delegate* unmanaged<byte*, void> cb)
{
    s_Callback = cb;
}
```

The `s_Callback` could be called when an error is meant to be written or could be passed into any export. An example of the native implementation would be:

```c
// char or wchar_t depending on if UTF-8 or UTF-16 encoding.
void callback(const char* msg)
{
    printf("%s\n", msg);
}
```

This could be written using native varargs but that isn't fully supported in .NET 5+ so I would recommend formatting the message in C# code and then passing it down to just write out via whatever native API is desired.

**Comment by AlexGer123** [comment]
First code sample has some syntax problems. This one:
```cs
// Callback can be byte* or ushort* depending on what encoding is being used.
private static delegate* unmanaged<byte*, void> s_Callback;
[UnmanagedCallersOnly]
public static void SetErrorMessageCallback(delegate* unmanaged<byte*, void> cb)
{
    s_Callback = cb;
}
```

But maybe lets try with a simple example:
```cs
        private static string ErrorMessage;
        public static void ReportError(string ErrorMessage)
        {
            Console.WriteLine(ErrorMessage);
            //Her I want to forward from C# to C to print out the error automatically
         }

        public static int SetData(string strText, int iNumber, double dNumber)
        {
            Console.WriteLine("C# Check Input from C:\nstrText " + strText + "\niNumber " + iNumber + "\ndNumber " + dNumber);
            if (strText == "Hello World" && iNumber == 1337 && dNumber == 23.123456)
            {
                return (int)CSharpLibrary.ErrorCode.eNO_ERROR;
            }
            else
            {
                ErrorMessage = string.Format("C# Check Input from C:\nstrText failed" + strText + "\niNumber " + iNumber + "\ndNumber " + dNumber);
                ReportError(ErrorMessage);
                return (int)CSharpLibrary.ErrorCode.eERROR;
            }
        }
```

For UnmanagedCallers
```cs
        [UnmanagedCallersOnlyAttribute(EntryPoint = "SetData")] //functions name for C interface
        public static int SetData([DNNE.C99Type("const char*")] System.IntPtr StringText, int intNumber, double doubleNumber)
        {
            var returnValue = CSharpLibrary.SetData(Marshal.PtrToStringAnsi(StringText), intNumber, doubleNumber);
            return returnValue;
        }
```

**Comment by AaronRobinsonMSFT** [comment]
>First code sample has some syntax problems.

What failures are you seeing? This example was compiled and ran without issue.

```csharp
        public static void ReportError(string ErrorMessage)
        {
            Console.WriteLine(ErrorMessage);
            //Her I want to forward from C# to C to print out the error automatically
         }
```

That is where one would call the `s_Callback` instead of `Console.WriteLine(ErrorMessage);`.

**Comment by AlexGer123** [comment]
I have no experience with callback. I know only the can be called any time.
![grafik](https://user-images.githubusercontent.com/8454972/122457980-928ef180-cfaf-11eb-9689-0f5fbc2ac20c.png)
Or I need add something? :)

**Comment by AlexGer123** [comment]
> That is where one would call the s_Callback instead of Console.WriteLine(ErrorMessage);.
It sounds so easy. But I dont know the syntax... :/

**Comment by AlexGer123** [comment]
Ah ok to solve the error it musst be

```cs
 unsafe class CSharpLibraryExport
```

**Comment by AaronRobinsonMSFT** [comment]
Yes, the `unsafe` keyword is needed on the class or method using the C# function pointer.  For the above the translation is similar to what you were doing in the example above.

```csharp
public static void ReportError(string ErrorMessage)
{
    // This allocates so must be freed in the callback or below.
    IntPtr str = Marshal.StringToCoTaskMemAnsi(ErrorMessage);

    // Pass the message down to the callback.
    s_Callback(str);

    // Can be omitted if freed in the callback. This location is more appropriate in my opinion.
    Marshal.FreeCoTaskMem(str);
}
```

**Comment by AlexGer123** [comment]
Ok. Thanks it build. :)

But something is with the C header wrong.
![grafik](https://user-images.githubusercontent.com/8454972/122465335-47c5a780-cfb8-11eb-8c01-72f7127c817d.png)
Have I forgotten anything?

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 What compiler are you using?

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 I reread the spec for C99 and it would appear that [`intptr_t` and `uintptr_t` are **optional** types](https://en.cppreference.com/w/c/types/integer). Perhaps your compiler doesn't support them? If so, I can relax the usage of them and instead defer to `void*`. You should be able to test this by using the [`DNNE.C99TypeAttribute`](https://github.com/AaronRobinsonMSFT/DNNE#native-code-customization)

**Comment by AlexGer123** [comment]
> @AlexGer123 What compiler are you using?

Unfortunately I work still with ANSI-C Compiler (if it is right...). My IDE is LabWindows CVI 6.0...this year is his twentieth birthday... :)
But we try very hard to change to Visual Studion for C/C++ programs.

**Comment by AlexGer123** [comment]
> @AlexGer123 I reread the spec for C99 and it would appear that [`intptr_t` and `uintptr_t` are **optional** types](https://en.cppreference.com/w/c/types/integer). Perhaps your compiler doesn't support them? If so, I can relax the usage of them and instead defer to `void*`. You should be able to test this by using the [`DNNE.C99TypeAttribute`](https://github.com/AaronRobinsonMSFT/DNNE#native-code-customization).
> 
> ```cs
> public static void SetErrorMessageCallback([DNNE.C99Type("void*")] delegate* unmanaged<byte*, void> cb)
> ```

This version build in C# and I can call it with unit test projekt but it breaks.
![image](https://user-images.githubusercontent.com/8454972/122524028-f77e3200-d017-11eb-896b-71bad68d5b17.png)
Really too bad I imagined it would be easier...

**Comment by AaronRobinsonMSFT** [comment]
>Unfortunately I work still with ANSI-C Compiler (if it is right...).

@AlexGer123 Thanks for confirming. Yes this is part of the issue. Not sure I will change that default (that is, `intptr_t`) but I will update the document for the workaround above.

Can you share the C# for the `GetData` function? Note this could be a runtime initialization issue. We can narrow it down using:

https://github.com/AaronRobinsonMSFT/DNNE/blob/2843c008de4c0bc0729a87aa56567d10012f108b/src/platform/dnne.h#L65-L67

**Comment by AlexGer123** [comment]
> Can you share the C# for the `GetData` function?

You mean like this: [InteroperabilityTest.zip](https://github.com/AaronRobinsonMSFT/DNNE/files/6678635/InteroperabilityTest.zip)

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 I took the supplied files and ran them locally without too much issue:

![image](https://user-images.githubusercontent.com/30635565/122621444-64aabb00-d04a-11eb-8df4-6b1ae1b48a12.png)

The code I used to execute this is below so you can copy/paste.

```c++
static void print(const char* msg)
{
    printf("%s\n", msg);
}

int main(int ac, const char **av)
{
    HMODULE hmod = LoadLibraryA(path);

    auto setCallback = (void(*)(void(*)(const char*)))GetProcAddress(hmod, "SetErrorMessageCallback");
    setCallback(print);

    auto fptr = (void(*)(char**,int*,double*))GetProcAddress(hmod, "GetData");

    char* str;
    int i;
    double d;
    fptr(&str, &i, &d);

    return EXIT_SUCCESS;
}
```

**Comment by AlexGer123** [comment]
Thanks for your effort. But I think I should change the IDE as soon as possible. From this point on I can fall back on your solution. Thanks. :)

![grafik](https://user-images.githubusercontent.com/8454972/122645082-c76a8800-d118-11eb-9d16-200b557e8bbe.png)

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 Don't give up so easily :-) This is C++ syntax and it appears you are restricted to C. Let me convert the code to C for you.

```c
static void print(const char* msg)
{
    printf("%s\n", msg);
}

int main(int ac, const char **av)
{
    char* str;
    int i;
    double d;
    HMODULE hmod = LoadLibraryA(path);

    void(*setCallback)(void(*)(const char*)) = (void(*)(void(*)(const char*)))GetProcAddress(hmod, "SetErrorMessageCallback");
    setCallback(print);

    void(*fptr)(char**,int*,double*)  = (void(*)(char**,int*,double*))GetProcAddress(hmod, "GetData");

    fptr(&str, &i, &d);

    return EXIT_SUCCESS;
}
```

**Comment by AlexGer123** [comment]
> @AlexGer123 Don't give up so easily :-)

I only have the worry that the way is very ineffective. :)
![grafik](https://user-images.githubusercontent.com/8454972/122680503-c193a600-d1ef-11eb-9fa0-f1ab7ca309dc.png)

**Comment by AaronRobinsonMSFT** [comment]
Sigh... wish I could get a copy of this compiler. I think the below is now proper ANSI-C. 

```c
static void print(const char* msg)
{
    printf("%s\n", msg);
}

int main(int ac, const char **av)
{
    char* str;
    int i;
    double d;
    HMODULE hmod;
    void(*setCallback)(void(*)(const char*));
    void(*fptr)(char**,int*,double*);

    hmod = LoadLibraryA(path);

    setCallback = (void(*)(void(*)(const char*)))GetProcAddress(hmod, "SetErrorMessageCallback");
    setCallback(print);

    fptr = (void(*)(char**,int*,double*))GetProcAddress(hmod, "GetData");
    fptr(&str, &i, &d);

    return EXIT_SUCCESS;
}
```

**Comment by AlexGer123** [comment]
Ok. Better.  👍  It Build but it crashes:
![grafik](https://user-images.githubusercontent.com/8454972/122681337-0b7e8b00-d1f4-11eb-8940-e3410e4ebbff.png)

**Comment by AaronRobinsonMSFT** [comment]
Excellent. So the issue here is 32-bit. That is fine. We can fix that by querying for the correct symbols.

~~`"SetErrorMessageCallback"`~~ -> `"_SetErrorMessageCallback@4"`
~~`"GetData"`~~ -> `"_GetData@12"`

You might also be able to drop the underscore (`_`) in the string &ndash; I don't recall how permissive `GetProcAddress` is in this case.

Alternatively you can switch to 64-bit where the above symbols will work. There are more options on the [`readme.md`](https://github.com/AaronRobinsonMSFT/DNNE#exporting-a-managed-function).

**Comment by AlexGer123** [comment]
I have understood where the problem is...calling convention at dll functions.
I can not use 64-bit to compile the dll (company restrictions). 
So this should work:
```cs
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void SetErrorMessageCallback([DNNE.C99Type("void*")] delegate* unmanaged<byte*, void> cb)
        {
            s_Callback = cb;
        }
```
**@AaronRobinsonMSFT** big thanks! 👍 
I will add this improvement soon to production.

![grafik](https://user-images.githubusercontent.com/8454972/122683555-3b339000-d200-11eb-8540-c28860c85288.png)
It this a problem if the calling convention for internal functions are still the same?

**Comment by AaronRobinsonMSFT** [comment]
>It this a problem if the calling convention for internal functions are still the same?

No. Those functions don't matter unless you specifically are calling them and you have specific constraints. Internally they are called but there is nothing you can do to break that functionality so it is entirely based on the constraints of your workflow and product.

I'm going to close this issue for now. Please don't hesitate to open a new issue if you hit other problems.

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 I'd like to follow up with you and ask a few general questions. If you are interested please email me. My address is in my GitHub profile. Thanks.

**Comment by AlexGer123** [comment]
I have one more question. :)

If I have two projects in one VS solution (one C# library project and one DNNE export project) how can I refer to callback over two projects without circular dependency problem?
![grafik](https://user-images.githubusercontent.com/8454972/123773452-f5945880-d8cc-11eb-92e4-4025069dd977.png)
I add an example too: 
[InteroperabilityTest.zip](https://github.com/AaronRobinsonMSFT/DNNE/files/6732215/InteroperabilityTest.zip)

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 I would move the `s_Callback` into `ClassLibrary1`. I don't really understand the confusion here though. You can forward the call to `ClassLibrary1`, create a 3rd assembly both assemblies share, or you can create a callback setter in `ClassLibrary1` that can callback into `InteroperabilityTest`. You can also merge most of the exports directly into `ClassLibrary1` directly if you like.

**Comment by AlexGer123** [comment]
@AaronRobinsonMSFT 
Ok. It makes no sense to separate the DNNE assembly in other VS project.
I split this because i'm still learning how everything works. But it works well without the split. Thanks :)
