### ISSUE TITLE
TypeResolver.GetTypeFromSerializedName implementation breaks when used on .NET 6.0

### ISSUE THREAD

**Issue by jkoritzinsky** [AaronRobinsonMSFT/DNNE#72]
Since DNNE runs on .NET 5, the `Type.GetType` calls in `TypeResolver.GetTypeFromSerializedName` break when DNNE runs against a .NET 6.0 assembly. The provided type names are assembly-qualified, so they try to load a 6.0 System.Runtime into DNNE, which runs against 5.0.

This could also be considered a "security issue" where a malicious library could provide a specialized attribute type in source with a different implementation that DNNE could find that DNNE would try to parse by calling `Type.GetType`  and would load malicious code into the process (this is the standard unbounded deserialization vulnerability as seen with BinaryFormatter and Newtonsoft.JSON).

https://github.com/AaronRobinsonMSFT/DNNE/blob/b31f877818070d1b71470f9303743b6687bd134b/src/dnne-gen/Generator.cs#L626-650

**Comment by AaronRobinsonMSFT** [comment]
>The provided type names are assembly-qualified, so they try to load a 6.0 System.Runtime into DNNE, which runs against 5.0.

Isn't the solution here to run with roll-forward with major? I guess it depends on what is being built though &ndash; boo. Suggestions on a way to address this? Is directly reading metadata?

**Comment by jkoritzinsky** [comment]
We could do that, but then the security issue is still present.

Also, generally we shouldn't be loading target assemblies into the process. We should follow the same design as Roslyn and the Crossgen2/Native AOT type system where the "target" type system is fully separate from the "in-proc" type system.

The solution I came up with is to do what we do in dotnet/runtime in a ton of places, and parse out the type name and assembly from the assembly-qualified name string manually.

**Comment by AaronRobinsonMSFT** [comment]
>The solution I came up with is to do what we do in dotnet/runtime in a ton of places, and parse out the type name and assembly from the assembly-qualified name string manually.

Ugh. Okay.
