### ISSUE TITLE
Litte beauty formatting without spaces

### ISSUE THREAD

**Issue by AlexGer123** [AaronRobinsonMSFT/DNNE#76]
Hi,

if I export with DNNE this lines for C header

![grafik](https://user-images.githubusercontent.com/8454972/124599004-833fed00-de65-11eb-8fa9-f58a92fad0b7.png)

the export has some (from far left) spaces like:
![grafik](https://user-images.githubusercontent.com/8454972/124599176-a79bc980-de65-11eb-921d-a70eb583f1f7.png)

It is possible to optimize the formatting?

**Comment by AaronRobinsonMSFT** [comment]
@AlexGer123 The insertion of from `C99DeclCode` attribute is direct and considered "literal". The best way to make it "pretty" is to remove the space from the C#.

```csharp
        // Header components for C export
        [DNNE.C99DeclCode(@"
// macros to call functions without
...
")];
```

**Comment by AlexGer123** [comment]
Ok. Thanks. :)
