### ISSUE TITLE
Request: Honor `SupportedOSPlatformAttribute` when emitting `.g.c` file.

### ISSUE THREAD

**Issue by obiwanjacobi** [AaronRobinsonMSFT/DNNE#82]
Would be nice if this would work...

```csharp
    public static Exports
    {
        [SupportedOSPlatform("windows")]
        [UnmanagedCallersOnly(EntryPoint = "GetPluginFactory")]
        public static IntPtr GetPluginFactory_Win()
        {  ...  }

        [SupportedOSPlatform("linux")]
        [UnmanagedCallersOnly(EntryPoint = "GetPluginFactory")]
        public static IntPtr GetPluginFactory_Lnx()
        {  ...  }
```

Currently (v1.0.23) there is an (C/C++) compiler error that indicates both variations are being emitted in the generated .c file.
Windows `error C2084: function 'intptr_t GetPluginFactory(void)' already has a body`
Linux `error G94CD4D9A: redefinition of 'GetPluginFactory'`

**Comment by AaronRobinsonMSFT** [comment]
@obiwanjacobi This wasn't too hard to add. Take a look at the PR #83 if you want. Feedback on the readme.md would be most appreciated. As soon as I can get @jkoritzinsky or someone with more experience with the .NET platform ecosystem I will merge it and publish a new package.

**Comment by obiwanjacobi** [comment]
Wow - you're fast! 👍 

Would this implementation also allow for the `SupportedOSPlatformAttribute` to be placed on the static class?
Readme looks ok.

```csharp
[SupportOSPlatform("windows")]
public static class WindowsExports
{
    public static IntPtr GetPluginFactory()
    { ... }
}

[SupportOSPlatform("linux")]
public static class LinuxExports
{
    public static IntPtr GetPluginFactory()
    { ... }
}
```

**Comment by obiwanjacobi** [comment]
Don't know of any examples, I've only seen it being used a couple of times - [but the attribute can be applied to almost anything](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-5.0).
In the context of this project, these two scenarios seem most likely/logical to me [2c].

**Comment by jkoritzinsky** [comment]
The canonical implementation for the platform attributes is as follows:

The attributes (Supported/UnsupportedOSPlatformAttribute) can each be applied at one of the following levels (generalized for simplicity):

- Assembly
- Module
- Type declaration
- Member declaration

At the highest level that any of the attributes are applied, either `SupportedOSPlatformAttribute` *or* `UnsupportedOSPlatformAttribute` may be applied. This defines an include/exclude list. Any deeper nested level (lower in the list) can apply `UnsupportedOSPlatformAttribute` to slim down the cases where the most global `SupportedOSPlatformAttribute` applies, or vice versa. Nested scopes cannot expand the include-list or exclude-list, only slim it down.

Here's a link to the design doc for the attributes: https://github.com/dotnet/designs/blob/main/accepted/2020/platform-exclusion/platform-exclusion.md#design

**Comment by AaronRobinsonMSFT** [comment]
@obiwanjacobi Published https://www.nuget.org/packages/DNNE/1.0.24
