### ISSUE TITLE
`internal static` is being generated code for?

### ISSUE THREAD

**Issue by obiwanjacobi** [AaronRobinsonMSFT/DNNE#86]
I am combining DNNE with the [ComWrappers API ](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers) which requires `[UnmanagedCallersOnly]` binary interface (vtables). These do resemble the DNNE prototypes, (static class, static methods with `[UnmanagedCallersOnly]` code attributes) but are implemented on an `internal static class`. It was my understanding that DNNE would only consider `public static class` static methods as candidates.

However I see in the generated .g.c file entries for my COM innterface interop methods (ABI)...

```cpp
...

#if (defined(DNNE_WINDOWS))
// Computed from ABI.IPluginFactoryManagedWrapper.CreateInstance
DNNE_API int32_t DNNE_CALLTYPE CreateInstance(intptr_t self, /* SUPPLY TYPE */ classId, /* SUPPLY TYPE */ interfaceId, intptr_t instance);
#endif // (DNNE_WINDOWS)

#if (defined(DNNE_WINDOWS))
// Computed from ComWrappersPlugin.PublicExport.GetPluginFactory
DNNE_API intptr_t DNNE_CALLTYPE GetPluginFactory(void);
#endif // (DNNE_WINDOWS)

...
```

The `GetPluginFactory()` is correct, the `CreateInstance()` is part of the internal ABI for COM interop (incorrect).

This could suggest the need for an `DnneIgnoreAttribute` code attribute to further tailor the exported functions in the native assembly.

---

Edit:

Fails: code is generated for `CreateInstance`.
```csharp
unsafe internal static class IPluginFactoryManagedWrapper
{
    [UnmanagedCallersOnly]
    public static Int32 CreateInstance(IntPtr self, ...) { ... }
}
```

Succeeds: no code is generated for `CreateInstance`.
```csharp
unsafe internal static class IPluginFactoryManagedWrapper
{
    [UnmanagedCallersOnly]
    internal static Int32 CreateInstance(IntPtr self, ...) { ... }
}
```

**Comment by AaronRobinsonMSFT** [comment]
@obiwanjacobi This is definitely a bug I will fix. Thanks for reporting it.

**Comment by AaronRobinsonMSFT** [comment]
@obiwanjacobi It would appear I misread this issue. I thought I'd regressed something recently but this is actually intentional. The readme.md states the following:

> The exported function must be marked static and public.

This check is only for the function and not the enclosing type. I suppose I could change this but it would be a breaking change at and one I'd be reluctant to introduce. The intention here is that the enclosing type might want to be hidden from the managed world but exposed as a native export. Do you have a scenario where the enclosing type is `internal` but a method with `UnmanagedCallersOnly` must be marked `public`?

**Comment by obiwanjacobi** [comment]
Fair enough. Perhaps explicitly mention that the class accessibility doesn't matter in the readme.md?
(I was thrown off because of how an internal class with public methods works in C#)

BTW: Would you know what the best place is for asking ComWrapper API questions?
