### ISSUE TITLE
Provide sample

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [AaronRobinsonMSFT/DNNE#9]
See CoreRT: https://github.com/dotnet/corert/tree/master/samples/NativeLibrary

**Comment by MeestorX** [comment]
Is there an example solution you can post that demonstrates this Native Exports function?

**Comment by AaronRobinsonMSFT** [comment]
@MeestorX An example exists in the form of a test scenario that I use prior to publishing. See https://github.com/AaronRobinsonMSFT/DNNE/tree/master/test/ExportingAssembly.

**Comment by MeestorX** [comment]
Thank you!

I don't expect you to debug my VS2019 install, but I've been struggling with this error for hours and cannot figure out what else I need to install or update. Maybe you can just point me in the right direction? I've attached the 3 build errors I receive.

[Exports Error.txt](https://github.com/AaronRobinsonMSFT/DNNE/files/5138006/Exports.Error.txt)

**Comment by MeestorX** [comment]
Here are the errors if you cannot download the above .txt file.

LNK2019	unresolved external symbol _get_hostfxr_path@12 referenced in function _load_hostfxr

LNK1120	1 unresolved externals

MSB3073	The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29213\bin\Hostx64\x86\cl.exe" /O2 /LD /TC /MT /GS /Zi /D DNNE_ASSEMBLY_NAME=ExportingAssembly /D DNNE_COMPILE_AS_SOURCE /I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29213\include" /I "C:\Users\Andy\.nuget\packages\dnne\1.0.7\tools\platform" /I "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\5.0.0-preview.8.20407.11\runtimes\win-x64\native" /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" "D:\Dropbox\Andy\Visual Studio 2019\Projects\ExportingAssembly\obj\Release\net5.0\dnne\ExportingAssembly.g.c" "C:\Users\Andy\.nuget\packages\dnne\1.0.7\tools\platform\platform.c"  /link /DLL /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29213\lib\x86" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x86" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\5.0.0-preview.8.20407.11\runtimes\win-x64\native\libnethost.lib" Advapi32.lib /IGNORE:4099 /IMPLIB:"D:\Dropbox\Andy\Visual Studio 2019\Projects\ExportingAssembly\obj\Release\net5.0\dnne\bin\ExportingAssemblyNE.lib" /OUT:"D:\Dropbox\Andy\Visual Studio 2019\Projects\ExportingAssembly\obj\Release\net5.0\dnne\bin\ExportingAssemblyNE.dll" " exited with code 2.

**Comment by AaronRobinsonMSFT** [comment]
@MeestorX Logs are always helpful. Thank you!

The issue seems to be: `"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\5.0.0-preview.8.20407.11\runtimes\win-x64\native\libnethost.lib"`. The x86 version should be used. I think you need to specify the specific RID in the project itself or switch to the `x64` configuration in Visual Studio.

**Comment by MeestorX** [comment]
Yep. Switching from "AnyCPU" to x64 fixed it. Thank you!
Will that affect cross-platform compatibility?

**Comment by AaronRobinsonMSFT** [comment]
>Will that affect cross-platform compatibility?

Kind of. The resulting .NET assembly will still be basically the same but the resulting native binary (`ExportingAssemblyNE.dll`) will be platform/architecture specific - I assume this is expected.

**Comment by MeestorX** [comment]
This library is only of use to me if it’s cross platform, ie it creates a
.dll, .dylib and .so file.

Am I expecting too ouch at this time?

**Comment by AaronRobinsonMSFT** [comment]
>This library is only of use to me if it’s cross platform, ie it creates a
.dll, .dylib and .so file.

That is a bit hard in practice. Platform specific tool chains aren't commonly supported for cross platform compilation. For example, compiling a macOS supported binary on a non-macOS platform is incredibly hard and in practice close to impossible for macOS. It isn't uncommon to cross-compile for architectures (i.e. compile ARM64 binary on a amd64 OS) though.

Solutions for this are using Docker images on a host machine and create the native binary that is used for the specific OS. The managed binary can be the same across all platforms/architectures etc, but that is up to the developer.

**Comment by MeestorX** [comment]
Ok, I see. Was hoping for a cross-platform solution. I have VS2019 for Mac and several MacOS machines for development, so that part is not an issue.

Do you have any links to more information on creating cross-platform libraries using .NET5.0?

**Comment by AaronRobinsonMSFT** [comment]
>Do you have any links to more information on creating cross-platform libraries using .NET5.0?

@MeestorX They will by default be cross-platform in the sense the .NET API is designed to run on all platforms. However, there are some functions/operations that aren't support cross-platform (e.g. COM support). Building a pure managed (.NET) assembly should load and run on any platform baring the developer writing code that makes platform assumptions.

Consider the case where a developer uses the `Process` class to run the `awk` command. This program isn't typically on a Windows platform and so has an implicit dependency on a *nix or macOS platform. Also, making assumptions about the side of `IntPtr` would be another case (i.e. `IntPtr.Size` is 8 on 64-bit platforms, but 4 on 32-bit platforms).

I don't think we have any guidance on how to ensure these kind of assumptions aren't made while developing a .NET library. Most of them require developers to write code that interacts with the OS or non .NET code - so perhaps that is the guidance?

Simply building a managed binary that calls .NET APIs will run on all platforms. There are cases, as mentioned above, where APIs may throw a [`PlatformNotSupportedException`](https://docs.microsoft.com/dotnet/api/system.platformnotsupportedexception) but those are typically documented.

**Comment by AaronRobinsonMSFT** [comment]
I believe the test example is a sufficient sample for now.
