### ISSUE TITLE
Build Nuget

### ISSUE THREAD

**Issue by climblinne** [AaronRobinsonMSFT/DNNE#95]
Hello,

we try to build the current source and generate the nuget by ourself. 

Could you give some hints, how to do it, because we always get some error message.

We tried:

``` 
dotnet build DNNE.sln
```
with installed .Net 6.0 RC2 SDK.
We get the following errors:

```
C:\work\cs\projects\DNNE2\test\ExportingAssembly\ExportingAssembly.csproj(7,3): error MSB4019: Das importierte Projekt "C:\work\cs\projects\DNNE2\src\dnne-pkg\bin\Debug\pkg\build\DNNE.props" wurde nicht gefunden. Stellen Sie sicher, dass der Ausdruck in der Import-Deklaration "C:\work\cs\projects\DNNE2\test\../src/dnne-pkg/bin/Debug/pkg/build/DNNE.props" richtig ist und dass die Datei auf dem Datenträger vorhanden ist.
C:\work\cs\projects\DNNE2\test\ExportingAssembly\ExportingAssembly.csproj(7,3): error MSB4019: Das importierte Projekt "C:\work\cs\projects\DNNE2\src\dnne-pkg\bin\Debug\pkg\build\DNNE.props" wurde nicht gefunden. Stellen Sie sicher, dass der Ausdruck in der Import-Deklaration "C:\work\cs\projects\DNNE2\test\../src/dnne-pkg/bin/Debug/pkg/build/DNNE.props" richtig ist und dass die Datei auf dem Datenträger vorhanden ist.
```

and also VS2019 (tried to use .NET5.0 again).

Best regards

Jan

**Comment by AaronRobinsonMSFT** [comment]
@climblinne Initially building from the `.sln` is going to be a poor experience. The project reference logic was a bit tricky and I couldn't get it to work correctly at all. The best approach is documented in the `readme.md`&mdash;see [Generating a native binary using the DNNE NuPkg](https://github.com/AaronRobinsonMSFT/DNNE#generating-a-native-binary-using-the-dnne-nupkg). The default for the `create_package.proj` project is to build in `Release` so if the desire is to build `Debug`, pass `-c Debug`.

After building `create_package.proj`, the `.sln` will work in the target flavor&mdash;`Release` or `Debug`.

**Comment by climblinne** [comment]
Thanks for the hint,  Aaron. How could I not see this in the documentation.
